site_name: AI Social Journal
site_url: https://yourdomain.com
site_author: Dinesh Gopal
site_description: "Making Sense of AI Together"

theme:
  name: material
  logo: assets/logo1.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: lime
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy

nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - RAG to Riches – Accessing LLMs: posts/rag-access-llms.md

plugins:
  - search
  - blogging:
      blog_dir: posts
      post_template: post.html
  - rss:
      site_url: https://yourdomain.com
  - git-revision-date-localized
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dineshgopal29
    - icon: fontawesome/brands/linkedin
      link: http://www.linkedin.com/in/dineshgopal1

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2025 Dinesh Gopal

