site_name: AI Social Journal
site_url: https://yourdomain.com
site_author: Dinesh Gopal
site_description: "Making Sense of AI Togethe"

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: deep purple
      accent: lime
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - RAG Chatbots: posts/rag-chatbots.md
      - Agentic Assistants: posts/agentic-assistants.md

plugins:
  - search
  - blogging:
      blog_dir: posts
      post_template: post.html
  - rss:
      site_url: https://yourdomain.com
  - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dineshgopal29
    - icon: fontawesome/brands/linkedin
      link: http://www.linkedin.com/in/dineshgopal1

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
